name: Make space
description: |
  Makes space on your worker node by deleting a lot of the software that
  comes pre-installed but that I don't really plan to use for doing work with
  nested VMs
runs:
  using: composite
  steps:
    - name: Delete all the things
      shell: bash
      if: runner.os == 'Linux'
      run: |
        set -ex -o pipefail
        sudo apt-get purge llvm\* php\*
        sudo rm -rf \
          /usr/local/{go1,julia,firefox,graalvm,aws-cli}* \
          /usr/share/{dotnet,rust,gradle,swift,miniconda,az_}* \
          /usr/lib/{llvm,google-cloud-sdk,jvm,mono,firefox,erlang}* \
          /usr/local/share/{vcpkg,powershell,chromium}* \
          /opt/{google,hhvm,pipx,az,ghc}
    - name: Delete all the things - macOS edition
      shell: bash
      if: runner.os == 'macOS'
      run: |
        echo "What do I delete?"
