name: Make space
description: |
  Makes space on your worker node by deleting a lot of the software that
  comes pre-installed but that I don't really plan to use for doing work with
  nested VMs
runs:
  using: composite
  steps:
    - name: Delete all the things
      shell: bash
      run: |
        set -ex -o pipefail
        sudo apt-get purge llvm\*
        sudo rm -rf \
          /usr/local/{go1,julia,firefox,graalvm,aws-cli}* \
          /usr/share/{dotnet,rust,gradle}* \
          /usr/lib/{llvm,google-cloud-sdk}*
