name: Make space
description: |
  Makes space on your worker node by deleting a lot of the software that
  comes pre-installed but that I don't really plan to use for doing work with
  nested VMs
runs:
  using: composite
  steps:
    - name: Delete all the things
      shell: bash
      if: runner.os == 'Linux'
      run: |
        set -ex -o pipefail
        sudo apt-get purge llvm\* php\*
        sudo rm -rf \
          /usr/local/aws-cli* \
          /usr/local/firefox* \
          /usr/local/go1* \
          /usr/local/graalvm* \
          /usr/local/julia*

        sudo rm -rf \
          /usr/share/az_* \
          /usr/share/doc \
          /usr/share/dotnet \
          /usr/share/fonts \
          /usr/share/gradle \
          /usr/share/java \
          /usr/share/kotlinc \
          /usr/share/man \
          /usr/share/miniconda \
          /usr/share/perl \
          /usr/share/sbt \
          /usr/share/swift \
          /usr/share/R \
          /usr/share/rust \
          /usr/share/vim

        sudo rm -rf \
          /usr/lib/erlang* \
          /usr/lib/firefox* \
          /usr/lib/google-cloud-sdk* \
          /usr/lib/heroku* \
          /usr/lib/jvm* \
          /usr/lib/llvm* \
          /usr/lib/mono* \
          /usr/local/share/{vcpkg,powershell,chromium}* \

        sudo rm -rf \
          /opt/az \
          /opt/ghc \
          /opt/google \
          /opt/hhvm \
          /opt/microsoft \
          /opt/pipx

    - name: Delete all the things - macOS edition
      shell: bash
      if: runner.os == 'macOS'
      run: |
        echo "What do I delete?"
