name: Test that it works

on:
  push:
    branches:
      - 'main'
  pull_request:
  workflow_dispatch:

jobs:
  test:
    name: Test that code works properly
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-11
          - macos-12
          - macos-13
          #- windows-latest
          - ubuntu-20.04
          - ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run this action
        uses: ./

      - name: Check diskspace on the host
        shell: bash
        if: startsWith(matrix.os, 'ubuntu')
        run: |
          set -ex
          df -h
          du -sh /usr/share/* | sort -h
          du -sh /usr/lib/* | sort -h
          sudo du -sh /usr/local/* | sort -h
          sudo du -sh /usr/local/share/* | sort -h
          sudo du -sh /opt/* | sort -h

      - name: Check diskspace on the host
        shell: bash
        if: startsWith(matrix.os, 'macos')
        run: |
          set -x
          sudo df -h
          sudo du -sh / | sort -h
          sudo du -sh /Applications | sort -h
