name: Test that it works

on:
  push:
  pull_request:

jobs:
  test:
    name: Test that code works properly
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          #- macos-latest
          #- windows-latest
          - ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
      - name: Check diskspace on the host
        shell: bash
        run: |
          set -ex
          du -sh /usr/share/* | sort -h
          du -sh /usr/lib/* | sort -h
          sudo du -sh /usr/local/* | sort -h
          sudo du -sh /usr/local/share/* | sort -h
          sudo du -sh /opt/* | sort -h
          df -h
